version: '3'
services:

    django-web:
      build: .
      ports:
        - "5050:5050"
    redis:
      image: "redis:alpine"
    mysql:
      image: "mysql"
      ports:
        - "3310:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
